import * as core from "./code.js";

const year = new Date().getFullYear();



export function exportCode(object) {
    const header = `/*
┏┓    •       ┳┳┓┏┓
┃ ┏┓┏┓┓┓┏┏┳┓  ┃┃┃┣ 
┗┛┗┛┣┛┗┗┻┛┗┗  ┻┻┛┗┛
    ┛              
Code generated by Copium IDE in ${year}.
https://copium-ide.github.io
*/

const Copium = {
    env: {
        version: "Copium-Lite",
    },
    assets: ${core.project.assets},
}

`;
    const modules = Object.keys(core.modules);
    const code = Object.keys(core.project.code);
    let script = header;
    for (let i = 0; i < modules.length; i++) { // Gather initialization scripts from the modules.
        script += modules[i].init();
    }
    for (let i = 0; i < code.length; i++) { // Parse project file and extract code.
        script += `
class ${code[i].name} {`; // Create class with the same name as the script.

        for (let j = 0; j < code[i].code.length; j++) {
            script += ``;
        }
        script += `
}`;
    }
} 
